version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::223035828796:user/aws-sam-cli-managed-dd-pipeline-resou-PipelineUser-1EG87Y6MMO71Z"

[dd]
[dd.pipeline_bootstrap]
[dd.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::223035828796:role/aws-sam-cli-managed-dd-pipel-PipelineExecutionRole-2CU920C1HSQZ"
cloudformation_execution_role = "arn:aws:iam::223035828796:role/aws-sam-cli-managed-dd-pi-CloudFormationExecutionR-1EGPTUHWE2G89"
artifacts_bucket = "aws-sam-cli-managed-dd-pipeline-r-artifactsbucket-p98ol5l4tjai"
image_repository = "223035828796.dkr.ecr.us-east-1.amazonaws.com/aws-sam-cli-managed-dd-pipeline-resources-imagerepository-n80ncibbhnnx"
region = "us-east-1"

[ddpipeline]
[ddpipeline.pipeline_bootstrap]
[ddpipeline.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::223035828796:role/aws-sam-cli-managed-ddpipeli-PipelineExecutionRole-1HXN8VB0QNIY6"
cloudformation_execution_role = "arn:aws:iam::223035828796:role/aws-sam-cli-managed-ddpip-CloudFormationExecutionR-M25U4TZH95X6"
artifacts_bucket = "aws-sam-cli-managed-ddpipeline-pi-artifactsbucket-13qccc9effz9e"
image_repository = "223035828796.dkr.ecr.us-east-1.amazonaws.com/aws-sam-cli-managed-ddpipeline-pipeline-resources-imagerepository-ijuegx0ovtxo"
region = "us-east-1"
